### ISSUE TITLE
Make Luminance an optional dependancy

### ISSUE THREAD

**Issue by Oregano1963** [MCLegoMan/Perspective#16]
From the mod page, it seems like Luminance is only for the Super Secret Settings. If a user isn't interested in such a feature, the Luminance dependency doesn't do much for them. If I am wrong and it does other things or is otherwise necessary for Perspective to function, please do tell.

**Comment by mclegoman** [comment]
Whilst Luminance is designed for shaders (and we use it for Super Secret Settings, and UI Background), it also handles some other things, such as translation keys, logging and versioning.
This is a library mod and is intended to be included inside Perspective so the end-user doesn't have to install anything.
Luminance will also help with compatibility with other shader mods that use it (e.g Souper Secret Settings).

I do realize there has been a couple versions where Luminance wasn't included in the jar, this is due to those versions using non-released versions of Luminance, future versions should hopefully always have Luminance embedded.
